spring.application.name=backend

# MongoDB
spring.mongodb.uri=${MONGO_URI:mongodb+srv://interviewx45_db_user:o0JfeUZlzyls9jLL@cluster0.rt5obto.mongodb.net/interviewx?retryWrites=true&w=majority&appName=Cluster0}
spring.mongodb.database=${MONGO_DATABASE:interviewx}

# Server
server.port=${PORT:8080}
server.address=0.0.0.0

# JWT
jwt.secret=${JWT_SECRET:YourVeryLongSecretKeyThatShouldBeAtLeast32CharactersLong}
jwt.expiration=86400000

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:gigzy45@gmail.com}
spring.mail.password=${MAIL_PASSWORD:ppiv uryh gkzq pyyz}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Google OAuth
google.client-id=${GOOGLE_CLIENT_ID:1068085438050-f8qr83tp0u0b4qp227cbs3hvfgqr241q.apps.googleusercontent.com}